# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Microsoft.UI.Xaml.Media

#include-once
#include "..\Classes\Microsoft.UI.Xaml.Media.Brush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.XamlCompositionBrushBase.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.AcrylicBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PathSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.ArcSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.BezierSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.CacheMode.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.BitmapCache.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.BrushCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.GeneralTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.Transform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.CompositeTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.CompositionTarget.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.SystemBackdrop.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.DesktopAcrylicBackdrop.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.DoubleCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.Geometry.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.EllipseGeometry.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.FontFamily.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.GeometryCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.GeometryGroup.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.GradientBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.GradientStop.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.GradientStopCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.TileBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.ImageBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.ImageSource.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.LineGeometry.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.LineSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.LinearGradientBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.LoadedImageSourceLoadCompletedEventArgs.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.LoadedImageSurface.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.Projection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.Matrix3DProjection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.MatrixHelper.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.MatrixTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.MediaTransportControlsThumbnailRequestedEventArgs.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.MicaBackdrop.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PathFigure.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PathFigureCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PathGeometry.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PathSegmentCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PlaneProjection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PointCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PolyBezierSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PolyLineSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.PolyQuadraticBezierSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.QuadraticBezierSegment.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.RadialGradientBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.RectangleGeometry.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.RenderedEventArgs.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.RenderingEventArgs.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.RotateTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.ScaleTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.Shadow.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.SkewTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.SolidColorBrush.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.ThemeShadow.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.TransformCollection.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.TransformGroup.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.TranslateTransform.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.VisualTreeHelper.au3"
#include "..\Classes\Microsoft.UI.Xaml.Media.XamlLight.au3"
