# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.UI.WebUI

#include-once
#include "..\Classes\Windows.UI.WebUI.ActivatedDeferral.au3"
#include "..\Classes\Windows.UI.WebUI.ActivatedOperation.au3"
#include "..\Classes\Windows.UI.WebUI.BackgroundActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.EnteredBackgroundEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.HtmlPrintDocumentSource.au3"
#include "..\Classes\Windows.UI.WebUI.IHtmlPrintDocumentSource.au3"
#include "..\Classes\Windows.UI.WebUI.LeavingBackgroundEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.NewWebUIViewCreatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.SuspendingDeferral.au3"
#include "..\Classes\Windows.UI.WebUI.SuspendingEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.SuspendingOperation.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIApplication.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIAppointmentsProviderAddAppointmentActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIAppointmentsProviderRemoveAppointmentActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIAppointmentsProviderReplaceAppointmentActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIAppointmentsProviderShowAppointmentDetailsActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIAppointmentsProviderShowTimeFrameActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIBackgroundTaskInstance.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIBackgroundTaskInstanceRuntimeClass.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIBarcodeScannerPreviewActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUICachedFileUpdaterActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUICameraSettingsActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUICommandLineActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactCallActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactMapActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactMessageActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactPanelActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactPickerActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactPostActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIContactVideoCallActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIDeviceActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIDevicePairingActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIDialReceiverActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIFileActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIFileOpenPickerActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIFileOpenPickerContinuationEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIFileSavePickerActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIFileSavePickerContinuationEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIFolderPickerContinuationEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUILaunchActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUILockScreenActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUILockScreenCallActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUILockScreenComponentActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUINavigatedDeferral.au3"
#include "..\Classes\Windows.UI.WebUI.WebUINavigatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUINavigatedOperation.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIPhoneCallActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIPrint3DWorkflowActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIPrintTaskSettingsActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIPrintWorkflowForegroundTaskActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIProtocolActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIProtocolForResultsActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIRestrictedLaunchActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUISearchActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIShareTargetActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIStartupTaskActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIToastNotificationActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIUserDataAccountProviderActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIView.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIVoiceCommandActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIWalletActionActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIWebAccountProviderActivatedEventArgs.au3"
#include "..\Classes\Windows.UI.WebUI.WebUIWebAuthenticationBrokerContinuationEventArgs.au3"
