# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.UI.Xaml

#include-once
#include "..\Classes\Windows.UI.Xaml.DependencyObject.au3"
#include "..\Classes\Windows.UI.Xaml.StateTriggerBase.au3"
#include "..\Classes\Windows.UI.Xaml.AdaptiveTrigger.au3"
#include "..\Classes\Windows.UI.Xaml.Application.au3"
#include "..\Classes\Windows.UI.Xaml.ApplicationInitializationCallbackParams.au3"
#include "..\Classes\Windows.UI.Xaml.BindingFailedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.BringIntoViewOptions.au3"
#include "..\Classes\Windows.UI.Xaml.RoutedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.BringIntoViewRequestedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.BrushTransition.au3"
#include "..\Classes\Windows.UI.Xaml.ResourceDictionary.au3"
#include "..\Classes\Windows.UI.Xaml.ColorPaletteResources.au3"
#include "..\Classes\Windows.UI.Xaml.UIElement.au3"
#include "..\Classes\Windows.UI.Xaml.FrameworkElement.au3"
#include "..\Classes\Windows.UI.Xaml.FrameworkTemplate.au3"
#include "..\Classes\Windows.UI.Xaml.CornerRadiusHelper.au3"
#include "..\Classes\Windows.UI.Xaml.DataContextChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.DataTemplate.au3"
#include "..\Classes\Windows.UI.Xaml.DataTemplateKey.au3"
#include "..\Classes\Windows.UI.Xaml.DebugSettings.au3"
#include "..\Classes\Windows.UI.Xaml.DependencyObjectCollection.au3"
#include "..\Classes\Windows.UI.Xaml.DependencyProperty.au3"
#include "..\Classes\Windows.UI.Xaml.DependencyPropertyChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.DispatcherTimer.au3"
#include "..\Classes\Windows.UI.Xaml.DragEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.DragOperationDeferral.au3"
#include "..\Classes\Windows.UI.Xaml.DragStartingEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.DragUI.au3"
#include "..\Classes\Windows.UI.Xaml.DragUIOverride.au3"
#include "..\Classes\Windows.UI.Xaml.DropCompletedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.DurationHelper.au3"
#include "..\Classes\Windows.UI.Xaml.EffectiveViewportChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.ElementFactoryGetArgs.au3"
#include "..\Classes\Windows.UI.Xaml.ElementFactoryRecycleArgs.au3"
#include "..\Classes\Windows.UI.Xaml.ElementSoundPlayer.au3"
#include "..\Classes\Windows.UI.Xaml.TriggerBase.au3"
#include "..\Classes\Windows.UI.Xaml.EventTrigger.au3"
#include "..\Classes\Windows.UI.Xaml.ExceptionRoutedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.FrameworkView.au3"
#include "..\Classes\Windows.UI.Xaml.FrameworkViewSource.au3"
#include "..\Classes\Windows.UI.Xaml.GridLengthHelper.au3"
#include "..\Classes\Windows.UI.Xaml.TriggerAction.au3"
#include "..\Classes\Windows.UI.Xaml.MediaFailedRoutedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.PointHelper.au3"
#include "..\Classes\Windows.UI.Xaml.PropertyMetadata.au3"
#include "..\Classes\Windows.UI.Xaml.PropertyPath.au3"
#include "..\Classes\Windows.UI.Xaml.RectHelper.au3"
#include "..\Classes\Windows.UI.Xaml.RoutedEvent.au3"
#include "..\Classes\Windows.UI.Xaml.ScalarTransition.au3"
#include "..\Classes\Windows.UI.Xaml.SetterBase.au3"
#include "..\Classes\Windows.UI.Xaml.Setter.au3"
#include "..\Classes\Windows.UI.Xaml.SetterBaseCollection.au3"
#include "..\Classes\Windows.UI.Xaml.SizeChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.SizeHelper.au3"
#include "..\Classes\Windows.UI.Xaml.StateTrigger.au3"
#include "..\Classes\Windows.UI.Xaml.Style.au3"
#include "..\Classes\Windows.UI.Xaml.TargetPropertyPath.au3"
#include "..\Classes\Windows.UI.Xaml.ThicknessHelper.au3"
#include "..\Classes\Windows.UI.Xaml.TriggerActionCollection.au3"
#include "..\Classes\Windows.UI.Xaml.TriggerCollection.au3"
#include "..\Classes\Windows.UI.Xaml.UIElementWeakCollection.au3"
#include "..\Classes\Windows.UI.Xaml.UnhandledExceptionEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Vector3Transition.au3"
#include "..\Classes\Windows.UI.Xaml.VisualState.au3"
#include "..\Classes\Windows.UI.Xaml.VisualStateChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.VisualStateGroup.au3"
#include "..\Classes\Windows.UI.Xaml.VisualStateManager.au3"
#include "..\Classes\Windows.UI.Xaml.VisualTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Window.au3"
#include "..\Classes\Windows.UI.Xaml.WindowCreatedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.XamlRoot.au3"
#include "..\Classes\Windows.UI.Xaml.XamlRootChangedEventArgs.au3"
