# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Networking.Sockets

#include-once
#include "..\Classes\Windows.Networking.Sockets.ControlChannelTrigger.au3"
#include "..\Classes\Windows.Networking.Sockets.DatagramSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.DatagramSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.DatagramSocketInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.DatagramSocketMessageReceivedEventArgs.au3"
#include "..\Classes\Windows.Networking.Sockets.IControlChannelTrigger.au3"
#include "..\Classes\Windows.Networking.Sockets.IDatagramSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IDatagramSocket2.au3"
#include "..\Classes\Windows.Networking.Sockets.IMessageWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IMessageWebSocket2.au3"
#include "..\Classes\Windows.Networking.Sockets.IMessageWebSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.IMessageWebSocketMessageReceivedEventArgs2.au3"
#include "..\Classes\Windows.Networking.Sockets.IServerMessageWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IServerStreamWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamSocket2.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamSocketListener.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamSocketListener2.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamWebSocket2.au3"
#include "..\Classes\Windows.Networking.Sockets.IStreamWebSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.IWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.IWebSocketControl2.au3"
#include "..\Classes\Windows.Networking.Sockets.IWebSocketInformation2.au3"
#include "..\Classes\Windows.Networking.Sockets.MessageWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.MessageWebSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.MessageWebSocketInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.au3"
#include "..\Classes\Windows.Networking.Sockets.ServerMessageWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.ServerMessageWebSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.ServerMessageWebSocketInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.ServerStreamWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.ServerStreamWebSocketInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.SocketActivityContext.au3"
#include "..\Classes\Windows.Networking.Sockets.SocketActivityInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.SocketActivityTriggerDetails.au3"
#include "..\Classes\Windows.Networking.Sockets.SocketError.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocketInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocketListener.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocketListenerConnectionReceivedEventArgs.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocketListenerControl.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamSocketListenerInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamWebSocket.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamWebSocketControl.au3"
#include "..\Classes\Windows.Networking.Sockets.StreamWebSocketInformation.au3"
#include "..\Classes\Windows.Networking.Sockets.WebSocketClosedEventArgs.au3"
#include "..\Classes\Windows.Networking.Sockets.WebSocketError.au3"
#include "..\Classes\Windows.Networking.Sockets.WebSocketKeepAlive.au3"
#include "..\Classes\Windows.Networking.Sockets.WebSocketServerCustomValidationRequestedEventArgs.au3"
