# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.UI.Xaml.Controls.Maps

#include-once
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileDataSource.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.CustomMapTileDataSource.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.HttpMapTileDataSource.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.LocalMapTileDataSource.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapActualCameraChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapActualCameraChangingEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElement.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapBillboard.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapCamera.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapContextRequestedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControl.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlBusinessLandmarkClickEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlBusinessLandmarkPointerEnteredEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlBusinessLandmarkPointerExitedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlBusinessLandmarkRightTappedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlDataHelper.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlTransitFeatureClickEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlTransitFeaturePointerEnteredEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlTransitFeaturePointerExitedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapControlTransitFeatureRightTappedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapCustomExperience.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapCustomExperienceChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElement3D.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementClickEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementPointerEnteredEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementPointerExitedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapLayer.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementsLayer.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementsLayerClickEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementsLayerContextRequestedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementsLayerPointerEnteredEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapElementsLayerPointerExitedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapIcon.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapInputEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapItemsControl.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapModel3D.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapPolygon.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapPolyline.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapRightTappedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapRouteView.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapScene.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapStyleSheet.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapStyleSheetEntries.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapStyleSheetEntryStates.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTargetCameraChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileBitmapRequest.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileBitmapRequestDeferral.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileBitmapRequestedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileSource.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileUriRequest.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileUriRequestDeferral.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.MapTileUriRequestedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.StreetsideExperience.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Maps.StreetsidePanorama.au3"
