# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Media.Audio

#include-once
#include "..\Classes\Windows.Media.Audio.AudioDeviceInputNode.au3"
#include "..\Classes\Windows.Media.Audio.AudioDeviceOutputNode.au3"
#include "..\Classes\Windows.Media.Audio.AudioEffectsPackConfiguration.au3"
#include "..\Classes\Windows.Media.Audio.AudioFileInputNode.au3"
#include "..\Classes\Windows.Media.Audio.AudioFileOutputNode.au3"
#include "..\Classes\Windows.Media.Audio.AudioFrameCompletedEventArgs.au3"
#include "..\Classes\Windows.Media.Audio.AudioFrameInputNode.au3"
#include "..\Classes\Windows.Media.Audio.AudioFrameOutputNode.au3"
#include "..\Classes\Windows.Media.Audio.AudioGraph.au3"
#include "..\Classes\Windows.Media.Audio.AudioGraphBatchUpdater.au3"
#include "..\Classes\Windows.Media.Audio.AudioGraphConnection.au3"
#include "..\Classes\Windows.Media.Audio.AudioGraphSettings.au3"
#include "..\Classes\Windows.Media.Audio.AudioGraphUnrecoverableErrorOccurredEventArgs.au3"
#include "..\Classes\Windows.Media.Audio.AudioNodeEmitter.au3"
#include "..\Classes\Windows.Media.Audio.AudioNodeEmitterConeProperties.au3"
#include "..\Classes\Windows.Media.Audio.AudioNodeEmitterDecayModel.au3"
#include "..\Classes\Windows.Media.Audio.AudioNodeEmitterNaturalDecayModelProperties.au3"
#include "..\Classes\Windows.Media.Audio.AudioNodeEmitterShape.au3"
#include "..\Classes\Windows.Media.Audio.AudioNodeListener.au3"
#include "..\Classes\Windows.Media.Audio.AudioPlaybackConnection.au3"
#include "..\Classes\Windows.Media.Audio.AudioPlaybackConnectionOpenResult.au3"
#include "..\Classes\Windows.Media.Audio.AudioStateMonitor.au3"
#include "..\Classes\Windows.Media.Audio.AudioSubmixNode.au3"
#include "..\Classes\Windows.Media.Audio.CreateAudioDeviceInputNodeResult.au3"
#include "..\Classes\Windows.Media.Audio.CreateAudioDeviceOutputNodeResult.au3"
#include "..\Classes\Windows.Media.Audio.CreateAudioFileInputNodeResult.au3"
#include "..\Classes\Windows.Media.Audio.CreateAudioFileOutputNodeResult.au3"
#include "..\Classes\Windows.Media.Audio.CreateAudioGraphResult.au3"
#include "..\Classes\Windows.Media.Audio.CreateMediaSourceAudioInputNodeResult.au3"
#include "..\Classes\Windows.Media.Audio.EchoEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.EqualizerBand.au3"
#include "..\Classes\Windows.Media.Audio.EqualizerEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.FrameInputNodeQuantumStartedEventArgs.au3"
#include "..\Classes\Windows.Media.Audio.IAudioDeviceInputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioDeviceOutputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioFileInputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioFileOutputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioFrameInputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioFrameOutputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioGraph.au3"
#include "..\Classes\Windows.Media.Audio.IAudioGraph2.au3"
#include "..\Classes\Windows.Media.Audio.IAudioInputNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioInputNode2.au3"
#include "..\Classes\Windows.Media.Audio.IAudioNode.au3"
#include "..\Classes\Windows.Media.Audio.IAudioNodeWithListener.au3"
#include "..\Classes\Windows.Media.Audio.IEchoEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.IEqualizerEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.ILimiterEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.IMediaSourceAudioInputNode.au3"
#include "..\Classes\Windows.Media.Audio.IReverbEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.LimiterEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.MediaSourceAudioInputNode.au3"
#include "..\Classes\Windows.Media.Audio.ReverbEffectDefinition.au3"
#include "..\Classes\Windows.Media.Audio.SetDefaultSpatialAudioFormatResult.au3"
#include "..\Classes\Windows.Media.Audio.SpatialAudioDeviceConfiguration.au3"
#include "..\Classes\Windows.Media.Audio.SpatialAudioFormatConfiguration.au3"
#include "..\Classes\Windows.Media.Audio.SpatialAudioFormatSubtype.au3"
