# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Networking.NetworkOperators

#include-once
#include "..\Classes\Windows.Networking.NetworkOperators.ESim.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimAddedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimDiscoverEvent.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimDiscoverResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimDownloadProfileMetadataResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimManager.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimOperationResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimPolicy.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimProfile.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimProfileMetadata.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimProfilePolicy.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimRemovedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimServiceInfo.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimUpdatedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ESimWatcher.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.HotspotAuthenticationContext.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.HotspotAuthenticationEventDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.HotspotCredentialsAuthenticationResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.KnownCSimFilePaths.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.KnownRuimFilePaths.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.KnownSimFilePaths.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.KnownUSimFilePaths.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandAccount.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandAccountEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandAccountUpdatedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandAccountWatcher.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandAntennaSar.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellCdma.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellGsm.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellLte.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellNR.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellTdscdma.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellUmts.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCellsInfo.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandCurrentSlotIndexChangedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceInformation.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceService.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceCommandEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceCommandResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceCommandSession.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceDataReceivedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceDataSession.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceInformation.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandDeviceServiceTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandModem.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandModemConfiguration.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandModemIsolation.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandNetwork.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandNetworkRegistrationStateChange.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandNetworkRegistrationStateChangeTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPco.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPcoDataChangeTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPin.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPinLockStateChange.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPinLockStateChangeTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPinManager.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandPinOperationResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandRadioStateChange.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandRadioStateChangeTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandSarManager.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandSlotInfo.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandSlotInfoChangedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandSlotManager.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandTransmissionStateChangedEventArgs.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandUicc.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandUiccApp.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandUiccAppReadRecordResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandUiccAppRecordDetailsResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.MobileBroadbandUiccAppsResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorDataUsageTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorNotificationEventDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorTetheringAccessPointConfiguration.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorTetheringClient.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorTetheringManager.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorTetheringOperationResult.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.NetworkOperatorTetheringSessionAccessPointConfiguration.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ProvisionFromXmlDocumentResults.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ProvisionedProfile.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.ProvisioningAgent.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.TetheringEntitlementCheckTriggerDetails.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.UssdMessage.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.UssdReply.au3"
#include "..\Classes\Windows.Networking.NetworkOperators.UssdSession.au3"
