# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.UI.Xaml.Media.Animation

#include-once
#include "..\Classes\Windows.UI.Xaml.Media.Animation.Transition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.AddDeleteThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EasingFunctionBase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.BackEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ConnectedAnimationConfiguration.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.BasicConnectedAnimationConfiguration.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.BeginStoryboard.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.BounceEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.CircleEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.Timeline.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ColorAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ColorAnimationUsingKeyFrames.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ColorKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ColorKeyFrameCollection.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.NavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.CommonNavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ConnectedAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ConnectedAnimationService.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ContentThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ContinuumNavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.CubicEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DirectConnectedAnimationConfiguration.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DiscreteColorKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DoubleKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DiscreteDoubleKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ObjectKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DiscreteObjectKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PointKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DiscretePointKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DoubleAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DoubleAnimationUsingKeyFrames.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DoubleKeyFrameCollection.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DragItemThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DragOverThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DrillInNavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DrillInThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DrillOutThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.DropTargetItemThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EasingColorKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EasingDoubleKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EasingPointKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EdgeUIThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ElasticEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EntranceNavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.EntranceThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ExponentialEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.FadeInThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.FadeOutThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.GravityConnectedAnimationConfiguration.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.KeySpline.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.KeyTimeHelper.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.LinearColorKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.LinearDoubleKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.LinearPointKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.NavigationThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ObjectAnimationUsingKeyFrames.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ObjectKeyFrameCollection.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PaneThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PointAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PointAnimationUsingKeyFrames.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PointKeyFrameCollection.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PointerDownThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PointerUpThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PopInThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PopOutThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PopupThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.PowerEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.QuadraticEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.QuarticEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.QuinticEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.ReorderThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.RepeatBehaviorHelper.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.RepositionThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.RepositionThemeTransition.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SineEase.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SlideNavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SplineColorKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SplineDoubleKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SplinePointKeyFrame.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SplitCloseThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SplitOpenThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.Storyboard.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SuppressNavigationTransitionInfo.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SwipeBackThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.SwipeHintThemeAnimation.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.TimelineCollection.au3"
#include "..\Classes\Windows.UI.Xaml.Media.Animation.TransitionCollection.au3"
