# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Devices.Sensors

#include-once
#include "..\Classes\Windows.Devices.Sensors.Accelerometer.au3"
#include "..\Classes\Windows.Devices.Sensors.AccelerometerDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.AccelerometerReading.au3"
#include "..\Classes\Windows.Devices.Sensors.AccelerometerReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.AccelerometerShakenEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.ActivitySensor.au3"
#include "..\Classes\Windows.Devices.Sensors.ActivitySensorReading.au3"
#include "..\Classes\Windows.Devices.Sensors.ActivitySensorReadingChangeReport.au3"
#include "..\Classes\Windows.Devices.Sensors.ActivitySensorReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.ActivitySensorTriggerDetails.au3"
#include "..\Classes\Windows.Devices.Sensors.AdaptiveDimmingOptions.au3"
#include "..\Classes\Windows.Devices.Sensors.Altimeter.au3"
#include "..\Classes\Windows.Devices.Sensors.AltimeterReading.au3"
#include "..\Classes\Windows.Devices.Sensors.AltimeterReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.Barometer.au3"
#include "..\Classes\Windows.Devices.Sensors.BarometerDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.BarometerReading.au3"
#include "..\Classes\Windows.Devices.Sensors.BarometerReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.Compass.au3"
#include "..\Classes\Windows.Devices.Sensors.CompassDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.CompassReading.au3"
#include "..\Classes\Windows.Devices.Sensors.CompassReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.DetectedPerson.au3"
#include "..\Classes\Windows.Devices.Sensors.Gyrometer.au3"
#include "..\Classes\Windows.Devices.Sensors.GyrometerDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.GyrometerReading.au3"
#include "..\Classes\Windows.Devices.Sensors.GyrometerReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.HeadOrientation.au3"
#include "..\Classes\Windows.Devices.Sensors.HeadPosition.au3"
#include "..\Classes\Windows.Devices.Sensors.HingeAngleReading.au3"
#include "..\Classes\Windows.Devices.Sensors.HingeAngleSensor.au3"
#include "..\Classes\Windows.Devices.Sensors.HingeAngleSensorReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.HumanPresenceFeatures.au3"
#include "..\Classes\Windows.Devices.Sensors.HumanPresenceSensor.au3"
#include "..\Classes\Windows.Devices.Sensors.HumanPresenceSensorReading.au3"
#include "..\Classes\Windows.Devices.Sensors.HumanPresenceSensorReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.HumanPresenceSensorReadingUpdate.au3"
#include "..\Classes\Windows.Devices.Sensors.HumanPresenceSettings.au3"
#include "..\Classes\Windows.Devices.Sensors.Inclinometer.au3"
#include "..\Classes\Windows.Devices.Sensors.InclinometerDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.InclinometerReading.au3"
#include "..\Classes\Windows.Devices.Sensors.InclinometerReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.LightSensor.au3"
#include "..\Classes\Windows.Devices.Sensors.LightSensorDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.LightSensorReading.au3"
#include "..\Classes\Windows.Devices.Sensors.LightSensorReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.LockOnLeaveOptions.au3"
#include "..\Classes\Windows.Devices.Sensors.Magnetometer.au3"
#include "..\Classes\Windows.Devices.Sensors.MagnetometerDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.MagnetometerReading.au3"
#include "..\Classes\Windows.Devices.Sensors.MagnetometerReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.OnlookerDetectionOptions.au3"
#include "..\Classes\Windows.Devices.Sensors.OrientationSensor.au3"
#include "..\Classes\Windows.Devices.Sensors.OrientationSensorReading.au3"
#include "..\Classes\Windows.Devices.Sensors.OrientationSensorReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.Pedometer.au3"
#include "..\Classes\Windows.Devices.Sensors.PedometerDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.PedometerReading.au3"
#include "..\Classes\Windows.Devices.Sensors.PedometerReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.ProximitySensor.au3"
#include "..\Classes\Windows.Devices.Sensors.ProximitySensorDataThreshold.au3"
#include "..\Classes\Windows.Devices.Sensors.ProximitySensorDisplayOnOffController.au3"
#include "..\Classes\Windows.Devices.Sensors.ProximitySensorReading.au3"
#include "..\Classes\Windows.Devices.Sensors.ProximitySensorReadingChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.SensorDataThresholdTriggerDetails.au3"
#include "..\Classes\Windows.Devices.Sensors.SensorQuaternion.au3"
#include "..\Classes\Windows.Devices.Sensors.SensorRotationMatrix.au3"
#include "..\Classes\Windows.Devices.Sensors.SimpleOrientationSensor.au3"
#include "..\Classes\Windows.Devices.Sensors.SimpleOrientationSensorOrientationChangedEventArgs.au3"
#include "..\Classes\Windows.Devices.Sensors.WakeOnApproachOptions.au3"
