# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.UI.Xaml.Controls.Primitives

#include-once
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ButtonBase.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ToggleButton.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.Selector.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.SelectorItem.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.FlyoutBase.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.PickerFlyoutBase.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.AppBarButtonTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.AppBarTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.AppBarToggleButtonTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.CalendarPanel.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.CalendarViewTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.CarouselPanel.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.RangeBase.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ColorPickerSlider.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ColorSpectrum.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ComboBoxTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBar.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBarTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.CommandBarTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.DragCompletedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.DragDeltaEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.DragStartedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.FlyoutBaseClosingEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.FlyoutShowOptions.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.GeneratorPositionHelper.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.GridViewItemPresenter.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.GridViewItemTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ItemsChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.JumpListItemBackgroundConverter.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.JumpListItemForegroundConverter.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.LayoutInformation.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenter.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ListViewItemTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.LoopingSelector.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.LoopingSelectorItem.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.LoopingSelectorPanel.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.MenuFlyoutItemTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.MenuFlyoutPresenterTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.OrientedVirtualizingPanel.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.PivotHeaderItem.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.PivotHeaderPanel.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.PivotPanel.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.Popup.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ProgressBarTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ProgressRingTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.RangeBaseValueChangedEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.RepeatButton.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ScrollBar.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ScrollEventArgs.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.SettingsFlyoutTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.SplitViewTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.Thumb.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.TickBar.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ToggleSwitchTemplateSettings.au3"
#include "..\Classes\Windows.UI.Xaml.Controls.Primitives.ToolTipTemplateSettings.au3"
