# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.ApplicationModel.Contacts

#include-once
#include "..\Classes\Windows.ApplicationModel.Contacts.AggregateContactManager.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.Contact.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactAddress.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactAnnotation.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactAnnotationList.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactAnnotationStore.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactBatch.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactCardDelayedDataLoader.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactCardOptions.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactChange.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactChangeReader.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactChangeTracker.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactChangedDeferral.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactChangedEventArgs.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactConnectedServiceAccount.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactDate.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactEmail.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactField.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactFieldFactory.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactGroup.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactInformation.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactInstantMessageField.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactJobInfo.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactLaunchActionVerbs.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactList.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactListLimitedWriteOperations.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactListSyncConstraints.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactListSyncManager.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactLocationField.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactManager.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactManagerForUser.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactMatchReason.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactPanel.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactPanelClosingEventArgs.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactPanelLaunchFullAppRequestedEventArgs.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactPhone.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactPicker.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactQueryOptions.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactQueryTextSearch.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactReader.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactSignificantOther.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactStore.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactStoreNotificationTriggerDetails.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.ContactWebsite.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.FullContactCardOptions.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContact2.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContact3.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactCardDelayedDataLoader.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactCardOptions2.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactInstantMessageField.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactLocationField.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactManagerStatics2.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactManagerStatics3.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactSignificantOther2.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactStore2.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.IContactWebsite2.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.KnownContactField.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.PinnedContactIdsQueryResult.au3"
#include "..\Classes\Windows.ApplicationModel.Contacts.PinnedContactManager.au3"
