# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Devices.PointOfService

#include-once
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScanner.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScannerCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScannerDataReceivedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScannerErrorOccurredEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScannerImagePreviewReceivedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScannerReport.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeScannerStatusUpdatedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeSymbologies.au3"
#include "..\Classes\Windows.Devices.PointOfService.BarcodeSymbologyAttributes.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawer.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerCloseAlarm.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerClosedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerEventSource.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerOpenedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerStatus.au3"
#include "..\Classes\Windows.Devices.PointOfService.CashDrawerStatusUpdatedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedBarcodeScanner.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedBarcodeScannerClosedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedCashDrawer.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedCashDrawerClosedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedJournalPrinter.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedLineDisplay.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedLineDisplayClosedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedMagneticStripeReader.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedMagneticStripeReaderClosedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedPosPrinter.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedPosPrinterClosedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedReceiptPrinter.au3"
#include "..\Classes\Windows.Devices.PointOfService.ClaimedSlipPrinter.au3"
#include "..\Classes\Windows.Devices.PointOfService.ICommonReceiptSlipCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.IReceiptOrSlipJob.au3"
#include "..\Classes\Windows.Devices.PointOfService.JournalPrintJob.au3"
#include "..\Classes\Windows.Devices.PointOfService.JournalPrinterCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplay.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayAttributes.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayCursor.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayCursorAttributes.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayCustomGlyphs.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayMarquee.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayStatisticsCategorySelector.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayStatusUpdatedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayStoredBitmap.au3"
#include "..\Classes\Windows.Devices.PointOfService.LineDisplayWindow.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReader.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderAamvaCardDataReceivedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderBankCardDataReceivedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderCardTypes.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderEncryptionAlgorithms.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderErrorOccurredEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderReport.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderStatusUpdatedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderTrackData.au3"
#include "..\Classes\Windows.Devices.PointOfService.MagneticStripeReaderVendorSpecificCardDataReceivedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinter.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterCharacterSetIds.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterFontProperty.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterPrintOptions.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterReleaseDeviceRequestedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterStatus.au3"
#include "..\Classes\Windows.Devices.PointOfService.PosPrinterStatusUpdatedEventArgs.au3"
#include "..\Classes\Windows.Devices.PointOfService.ReceiptPrintJob.au3"
#include "..\Classes\Windows.Devices.PointOfService.ReceiptPrinterCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.SlipPrintJob.au3"
#include "..\Classes\Windows.Devices.PointOfService.SlipPrinterCapabilities.au3"
#include "..\Classes\Windows.Devices.PointOfService.UnifiedPosErrorData.au3"
