# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Media.Playback

#include-once
#include "..\Classes\Windows.Media.Playback.BackgroundMediaPlayer.au3"
#include "..\Classes\Windows.Media.Playback.CurrentMediaPlaybackItemChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.ICurrentMediaPlaybackItemChangedEventArgs2.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackItem.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackItem2.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackItem3.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackItemFactory2.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackList.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackList2.au3"
#include "..\Classes\Windows.Media.Playback.IMediaPlaybackList3.au3"
#include "..\Classes\Windows.Media.Playback.IPlaybackMediaMarkerSequence.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreak.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreakEndedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreakManager.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreakSchedule.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreakSeekedOverEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreakSkippedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaBreakStartedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaItemDisplayProperties.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackAudioTrackList.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManager.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerAutoRepeatModeReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerCommandBehavior.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerFastForwardReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerNextReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerPauseReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerPlayReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerPositionReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerPreviousReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerRateReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerRewindReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackCommandManagerShuffleReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackItem.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackItemError.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackItemFailedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackItemOpenedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackList.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackSession.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackSessionBufferingStartedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackSessionOutputDegradationPolicyState.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackSphericalVideoProjection.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackTimedMetadataTrackList.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlaybackVideoTrackList.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlayer.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlayerDataReceivedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlayerFailedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlayerRateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.MediaPlayerSurface.au3"
#include "..\Classes\Windows.Media.Playback.PlaybackMediaMarker.au3"
#include "..\Classes\Windows.Media.Playback.PlaybackMediaMarkerReachedEventArgs.au3"
#include "..\Classes\Windows.Media.Playback.PlaybackMediaMarkerSequence.au3"
#include "..\Classes\Windows.Media.Playback.TimedMetadataPresentationModeChangedEventArgs.au3"
