# *** WinRT by MattyD v1.7.1 ***
# This project is still in development. Expect bugs in some libraries!
# --------------------------------------------------------------------
# Generated : 08 May 2026
# Platform  : WIN_11 25H2 26200
# WinAppSDK : 2.0 
# File Type : Namespace
# File Name : Windows.Media.Capture

#include-once
#include "..\Classes\Windows.Media.Capture.AdvancedCapturedPhoto.au3"
#include "..\Classes\Windows.Media.Capture.AdvancedPhotoCapture.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastBackgroundService.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastBackgroundServiceSignInInfo.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastBackgroundServiceStreamInfo.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastCameraCaptureStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastGlobalSettings.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastHeartbeatRequestedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastManager.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastMicrophoneCaptureStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPlugIn.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPlugInManager.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPlugInStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPreview.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPreviewStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPreviewStreamReader.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPreviewStreamVideoFrame.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastPreviewStreamVideoHeader.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastProviderSettings.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastServices.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastSignInStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastState.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastStreamAudioFrame.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastStreamAudioHeader.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastStreamReader.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastStreamStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastStreamVideoFrame.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastStreamVideoHeader.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastTriggerDetails.au3"
#include "..\Classes\Windows.Media.Capture.AppBroadcastViewerCountChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppCapture.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureAlternateShortcutKeys.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureDurationGeneratedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureFileGeneratedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureManager.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureMetadataWriter.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureMicrophoneCaptureStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureRecordOperation.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureRecordingStateChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureServices.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureSettings.au3"
#include "..\Classes\Windows.Media.Capture.AppCaptureState.au3"
#include "..\Classes\Windows.Media.Capture.CameraCaptureUI.au3"
#include "..\Classes\Windows.Media.Capture.CameraCaptureUIPhotoCaptureSettings.au3"
#include "..\Classes\Windows.Media.Capture.CameraCaptureUIVideoCaptureSettings.au3"
#include "..\Classes\Windows.Media.Capture.CameraOptionsUI.au3"
#include "..\Classes\Windows.Media.Capture.CapturedFrame.au3"
#include "..\Classes\Windows.Media.Capture.CapturedFrameControlValues.au3"
#include "..\Classes\Windows.Media.Capture.CapturedPhoto.au3"
#include "..\Classes\Windows.Media.Capture.GameBarServices.au3"
#include "..\Classes\Windows.Media.Capture.GameBarServicesCommandEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.GameBarServicesManager.au3"
#include "..\Classes\Windows.Media.Capture.GameBarServicesManagerGameBarServicesCreatedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.GameBarServicesTargetInfo.au3"
#include "..\Classes\Windows.Media.Capture.ICapturedFrame.au3"
#include "..\Classes\Windows.Media.Capture.LowLagMediaRecording.au3"
#include "..\Classes\Windows.Media.Capture.LowLagPhotoCapture.au3"
#include "..\Classes\Windows.Media.Capture.LowLagPhotoSequenceCapture.au3"
#include "..\Classes\Windows.Media.Capture.MediaCapture.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureDeviceExclusiveControlStatusChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureFailedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureFocusChangedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureInitializationSettings.au3"
#include "..\Classes\Windows.Media.Capture.MediaCapturePauseResult.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureRelativePanelWatcher.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureSettings.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureStopResult.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureVideoProfile.au3"
#include "..\Classes\Windows.Media.Capture.MediaCaptureVideoProfileMediaDescription.au3"
#include "..\Classes\Windows.Media.Capture.OptionalReferencePhotoCapturedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.PhotoCapturedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.PhotoConfirmationCapturedEventArgs.au3"
#include "..\Classes\Windows.Media.Capture.VideoStreamConfiguration.au3"
